version: "3.3"

services:
  app:
    container_name: "app"
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      - PORT=8080
    command: npm start
  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=myadmin
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  node_modules:
